Pizzeria/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    
]

pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('',views.index,name='index'),
    path('pizzas',views.pizzas,name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),
    path('new_review/<int:pizza_id>/',views.new_review,name='new_review'),
]

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    pizza_name = models.CharField(max_length=20)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=40)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.topping_name

class Review(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    review = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review

pizzas/forms.py
from django import forms

from .models import *

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

pizzas/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *


# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.order_by('pizza_name')

    context = {'all_pizzas':pizzas}                 #key is variable name used in html file. Value is variable name usin in view

    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    p = Pizza.objects.get(id=pizza_id)

    toppings = Topping.objects.filter(pizza=p)

    reviews = Review.objects.filter(pizza=p)

    context = {'pizza':p, 'toppings':toppings, 'reviews':reviews} 

    return render(request, 'pizzas/pizza.html', context)

def new_review(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = ReviewForm()
    else:
        form = ReviewForm(data=request.POST)
        if form.is_valid():
            new_review = form.save(commit=False)
            new_review.pizza = pizza
            new_review.save()
            return redirect('pizzas:pizza',pizza_id=pizza_id)
    
    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzas/new_review.html', context)

    

pizzas/templates/pizzas/base.html
{% load bootstrap4 %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
     shrink-to-fit=no">

    <title>Pizzeria</title>

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
</head>




<body>

    <style>
        body {
          background-image: url('https://cdn.pixabay.com/photo/2020/03/21/02/26/pizza-4952509_960_720.jpg');
          background-repeat: no-repeat;
          background-attachment: fixed;
          background-size: 100% 100%;
        }
        </style>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    
        <a class="navbar-brand" href="{% url 'pizzas:index'%}">Pizzeria</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pizzas:pizzas'%}">
                 Pizzas</a></li>
         </ul>
    </div>
    </nav>


    <main role="main" class="container">


        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
         </div>
         <body>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
    
</body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}



{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Welcome to Slice of Heaven!</h1>
    
    <p class="lead">There is a pizza for everyone here!</p>

</div>




  {% endblock page_header %}

  {% block content %}

  <pre>
    <span style="color:white; font-size:medium;">
        In the bustling city, amidst the hustle and bustle,
        A little slice of heaven lies nestled,
        
        A pizzeria, with a warm and inviting glow,
        Where deliciousness awaits, ready to go,
        
        With pizzas that are made with love and care,
        Each bite a symphony of flavors, truly rare,
        
        The crust is crispy, the cheese is gooey,
        A taste sensation that's out of this world, truly,
        
        But it's not just the pizza that makes this place divine,
        It's the atmosphere, the laughter, the smiles that shine,
        
        Here, everyone is welcome, no matter who you are,
        Come one, come all, to A Slice of Heaven Pizzeria,
        
        A little slice of heaven, right here on earth,
        Where the pizza is always hot, and the love flows from the hearth.
</span>
</pre>
{% endblock content %}

pizzas/templates/pizzas/new_review.html
{% extends "pizzas/base.html" %}

{% block content %}

<h3><p><a href="{% url 'pizzas:pizza' pizza.id %}"><span style="color:white">{{pizza}}</span></a></p></h3>



<span style="color:white">
<p>Add new review:</p>
</span>
<span style="color:white">
<form action="{% url 'pizzas:new_review' pizza.id %}" method="post">
</span>
    {% csrf_token %}

    {{ form.as_p }}
    
    <button name="submit">Add review</button>

</form>


{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block page_header %}
    <h3><span style="color:white">{{pizza}}</span></h3>
{% endblock page_header %}

{% block content %}
<img class="card-img-top" src="..." alt="Card image cap">
<ul>
    {% for t in toppings %}

    <span style="color:white"><li><h3> {{ t.topping_name }} </h3></li></span>

    {% empty %}
    <li><h3> No toppings for this pizza have been added yet.</h3></li>
    {% endfor %}

</ul>

<p>
    <h3><a href="{% url 'pizzas:new_review' pizza.id %}">Add a new review</a></h3>
</p>

<ul>
    {% for r in reviews %}
    <div class="background">
        <span style="color:white">
            <h4 class="card-header">
            {{ r.review|linebreaks }}
            </h4>
        </span>
        <span style="color:white"><div class="card-body">
        {{ r.date_added|date:'M d, Y H:i' }}
    </span>
        </div>
    </div>


    {% empty %}
    <span style="color:white">
    <P> No reviews for this pizza have been added yet.</p>
    </span>
    {% endfor %}

</ul>





{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}


<h3>
    <p>
        <span style="text-decoration: underline; color:white"> Pizzas </span>
    </p>
</h3>

<ul>
    {% for pizza in all_pizzas %}





      <div class="card" style="width: 18rem;">
        <h5 class="card-title">{{pizza}}</h5>
        <img class="card-img-top" src="..." alt="Card image cap">
        <div class="card-body">
          <a href="{% url 'pizzas:pizza' pizza.id %}"> View Pizza </a>
        </div>
      </div>
    {% empty %}
    <li> No pizzas have been added yet.</li>
    {% endfor %}

</ul>

{% endblock content %}